apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.10.0.118 # master ip
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.22.10 # 설치한 kubeadm, kubelet, kubectl과 동일한 버전
controlPlaneEndpoint: 10.10.0.118:6443 # master ip 지정, port는 반드시 6443
imageRepository: k8s.gcr.io
networking:
  serviceSubnet: 172.168.200.0/24 # 사용할 service의 ip cidr
  podSubnet: 10.244.0.0/16 # --pod-network-cidr for using with flannel
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

