apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mysql
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: qwer1234
            - name: MYSQL_DATABASE # 구성할 database명
              value: connectdb
            - name: MYSQL_ROOT_HOST # 접근 호스트
              value: '%'
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
spec:
  clusterIP: 172.168.200.160
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306

